# Generated by Django 4.1.3 on 2022-11-21 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='Иван', max_length=50, verbose_name='Имя')),
                ('lastName', models.CharField(help_text='Иванов', max_length=100, verbose_name='Фамилия')),
                ('birth', models.DateField(blank=True)),
                ('grade', models.PositiveSmallIntegerField(default=1, help_text='Оценка от 1 до 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('text', models.TextField(help_text='Напишите свой отзыв...', verbose_name='Отзыв')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
