# Generated by Django 4.1.3 on 2022-11-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='firstName',
            field=models.CharField(help_text='Иван', max_length=40, verbose_name='Имя'),
        ),
    ]
