# Generated by Django 4.1.3 on 2022-11-21 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='birth',
            field=models.DateField(blank=True, help_text='DD-MM-YYYY', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.PositiveSmallIntegerField(default=1, help_text='Оценка от 1 до 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Оценка'),
        ),
    ]
