# Generated by Django 4.1.3 on 2022-11-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=150, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Cтатья',
                'verbose_name_plural': 'Cтатьи',
            },
        ),
    ]
